<?php

/**
 * @file
 * Module hooks.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\block\BlockInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function draft_core_preprocess_commerce_cart_block(&$variables) {
  $variables['icon']['#uri'] = 'modules/contrib/commerce/icons/5181c6/cart.svg';
}

/**
 * Implements hook_theme().
 */
function draft_core_theme($existing, $type, $theme, $path) {
  return [
    'block__primary_menu__id__solr_search_form_narrow' => [
      'render element' => 'elements',
      'template' => 'block--primary-menu--id--solr-search-form-narrow',
      'base hook' => 'block'
    ],
    'block__secondary_menu__id__solr_search_form_wide' => [
      'render element' => 'elements',
      'template' => 'block--secondary-menu--id--solr-search-form-wide',
      'base hook' => 'block'
    ],
    'form__search_block_form' => [
      'render element' => 'elements',
      'template' => 'form--search-block-form',
      'base hook' => 'form'
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK()
 */
function draft_core_preprocess_block(&$variables) {
  if (!empty($variables['elements']['#id'])) {
    /** @var \Drupal\block\BlockInterface $block */
    $block = \Drupal::entityTypeManager()
      ->getStorage('block')
      ->load($variables['elements']['#id']);
    if ($block instanceof BlockInterface) {
      $region = $block->getRegion();

      if ($variables['base_plugin_id'] === 'views_exposed_filter_block') {
        if ($region === 'primary_menu') {
          $variables['#attached']['library'][] = 'olivero/search-narrow';
          $variables['content']['actions']['submit']['#theme_wrappers'] = ['input__submit__header_search'];
        }
        elseif ($region === 'secondary_menu') {
          $variables['#attached']['library'][] = 'olivero/search-wide';
          $variables['content']['actions']['submit']['#theme_wrappers'] = ['input__submit__header_search'];
        }
      }
    }
  }

}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for form templates.
 */
function draft_core_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if ($variables['element']['#form_id'] === 'views_exposed_form') {
    $suggestions[] = 'form__search_block_form';
  }
}

/**
 * Implements hook_form_alter() for adding classes and placeholder text to the search forms.
 */
function draft_core_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['actions']['submit']) && (count($form['actions'])) <= 2) {
    $form['actions']['submit']['#attributes']['class'][] = 'button--primary';
  }

  if ($form_id == 'views_exposed_form') {
    $form['filter']['#attributes']['placeholder'] = t('Search by keyword or phrase.');
    $form['filter']['#type'] = 'search';
    $form['actions']['submit']['#attributes']['class'][] = 'search-form__submit';
    $form['#attached']['library'][] = 'olivero/navigation-primary';
  }
}

/**
 * Implements hook_preprocess_form_element().
 */
function draft_core_preprocess_form_element(&$variables) {
  if ($variables['type'] == 'search') {
    $variables['attributes']['class'][] = 'form-item-keys';
  }
}
