<?php

/**
 * @file
 * Primary module hooks for Draft Cart module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function draft_breadcrumbs_preprocess_breadcrumb(&$variables) {
  $route_match = Drupal::routeMatch();
  if ($route_match->getRouteName() == 'entity.commerce_product.canonical') {
    $product_name = $variables['breadcrumb'][1];
    $product = $route_match->getParameter('commerce_product');
    $category = $product->get('categories')->first()->entity;
    $id = $category->id();
    $name = $category->label();
    $product_with_category = [
      'text' => $name,
      'url' => '/taxonomy/term/' . $id,
    ];
    $variables['breadcrumb'][1] = $product_with_category;
    $variables['breadcrumb'][2] = $product_name;
    $variables['#cache']['contexts'][] = 'route';
  }

}
