# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysqldb:
    type: mysql:10.4
    disk: 1024

cache:
  type: redis:6.0

searchsolr:
  type: solr:8.6
  disk: 1024
  configuration:
    cores:
      maincore:
        conf_dir: !archive "solr_8.x_config/"
    endpoints:
      main:
        core: maincore

elasticsearch:
  type: elasticsearch:7.10
  disk: 512
