name: Enable automerge

on:
  pull_request_target:
    types: [opened, reopened, labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - name: Automatically Merge PR
        uses: plm9606/automerge_actions@1.2.2
        with:
          label-name: "automerge"
          reviewers-number: 1
          # The merge method ("merge", "squash", "rebase"). Default is "merge"
          merge-method: "merge"
          # Let the bot delete the merged branch. true or false.
          auto-delete: true
          # GitHub WebHook Secret Token
          github-token: ${{ secrets.CI_TOKEN }}
