name: Drupal coding standards

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress -vvv
      - name: Run PHPCS with DrupalPractice on modules
        uses: docker://hussainweb/drupalqa:php7.4
        with:
          args: ./vendor/bin/phpcs -np
