name: Drupal coding standards

on: [pull_request]
jobs:
  code-standard:
    name: Drupal code standards check
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: '7.4'
      COMPOSER_VERSION: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Some tests run Composer via command line. It's not possible to require
      # a package in the detached state. Checkout to a branch to workaround
      # this.
      - name: Checkout to a branch
        run: git switch -c test

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${PHP_VERSION}
          tools: composer:v${COMPOSER_VERSION}

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: php-${PHP_VERSION}-${COMPOSER_VERSION}-${{ hashFiles('composer.lock') }}
          restore-keys: php-${PHP_VERSION}-${COMPOSER_VERSION}-

      - name: Install Composer dependencies
        run: composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Coding standards
        run: vendor/bin/phpcs

      - name: Static Code Analysis
        run: vendor/bin/phpstan analyse

      - name: Tests
        run: vendor/bin/phpunit
